language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t lahnaoja/multi-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lahnaoja/multi-test npm test

after_success:
  - docker build -t lahnaoja/multi-client ./client
  - docker build -t lahnaoja/multi-nginx ./nginx
  - docker build -t lahnaoja/multi-server ./server
  - docker build -t lahnaoja/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push lahnaoja/multi-client
  - docker push lahnaoja/multi-nginx
  - docker push lahnaoja/multi-server
  - docker push lahnaoja/multi-worker
